### ISSUE TITLE
Deprecate Uber, add Lyft support

### ISSUE THREAD

**Issue by Caleb-An** [jaebradley/uber-cli#18]
Uber's a [terrible company](https://www.susanjfowler.com/blog/2017/2/19/reflecting-on-one-very-strange-year-at-uber) that many people are boycotting. Lyft [has a rich API as well](https://developer.lyft.com/docs), I think this would gain more traction if it supported Lyft instead (or at least the option of both).

**Comment by modelorona** [comment]
At the current moment Lyft has no presence outside of the US and thus removing it would make no sense. The sensible solution would be to support both but that is up to the developer.

**Comment by jaebradley** [comment]
![alt-text](https://media.giphy.com/media/aLdiZJmmx4OVW/giphy.gif)

**Comment by djstein** [comment]
While I agree with the sentiment this is "Uber CLI" not "Lyft CLI" nor every other ride service. This is not a technical issue. @jaebradley wanna close this issue? And to everyone else, is there a want/need to make a CLI tool for other ride services. Possibly fork or recreate with options for other services?

**Comment by yjkimjunior** [comment]
😂 +1 on a separate Lyft CLI though

**Comment by jreynojustin** [comment]
Not sure how good it is but someone has made a Lyft CLI @ https://github.com/iampark/lyft-cli

**Comment by iSamMitchell** [comment]
I agree with the whole Lyft CLI thing, but @modelorona is right, they [haven't expanded](https://blog.lyft.com/posts/lyft-launches-biggest-expansion-yet) outside of the US: 

![Lyft Locations](https://static1.squarespace.com/static/5330a423e4b07cae635bb95e/t/58ade7686a49630fea9c939c/1487792045286/bigfoot_blog_reduced.gif?format=1500w)

**Comment by jaebradley** [comment]
@Caleb-An I appreciate the candor and wit but @djstein [brings up valid reasons](https://github.com/jaebradley/uber-cli/issues/18#issuecomment-282213572) to close this issue.
