### ISSUE TITLE
Enumify Symbol is not defined

### ISSUE THREAD

**Issue by briansoule** [jaebradley/uber-cli#21]
After building from source, and installing requests, I received this error:
```
/usr/local/lib/node_modules/uber-cli/node_modules/enumify/lib/enumify.js:14
var INITIALIZED = Symbol();
                  ^
ReferenceError: Symbol is not defined
    at Object.<anonymous> (/usr/local/lib/node_modules/uber-cli/node_modules/enumify/lib/enumify.js:14:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/uber-cli/node_modules/uber-client/build/data/Subpath.js:8:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/uber-cli/node_modules/uber-client/build/UberClient.js:22:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/uber-cli/node_modules/uber-client/build/index.js:4:19)
```

**Comment by jaebradley** [comment]
@briansoule certainly an interesting error - do you mind providing your `node` and `npm` version?

**Comment by markmark1** [comment]
I got the same error too 

> var INITIALIZED = Symbol();
>                   ^
> ReferenceError: Symbol is not defined
>     at Object.<anonymous> (/usr/local/lib/node_modules/uber-cli/node_modules/enumify/lib/enumify.js:14:19)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/usr/local/lib/node_modules/uber-cli/node_modules/uber-client/build/data/Subpath.js:8:16)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/usr/local/lib/node_modules/uber-cli/node_modules/uber-client/build/UberClient.js:22:16)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/usr/local/lib/node_modules/uber-cli/node_modules/uber-client/build/index.js:4:19)
> xx@xxs-Macbook-Air-3 ~ $ uber time '820 kipling street palo alto ca 94301'
> 
> /usr/local/lib/node_modules/uber-cli/node_modules/enumify/lib/enumify.js:14
> var INITIALIZED = Symbol();
>                   ^
> ReferenceError: Symbol is not defined
>     at Object.<anonymous> (/usr/local/lib/node_modules/uber-cli/node_modules/enumify/lib/enumify.js:14:19)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/usr/local/lib/node_modules/uber-cli/node_modules/uber-client/build/data/Subpath.js:8:16)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/usr/local/lib/node_modules/uber-cli/node_modules/uber-client/build/UberClient.js:22:16)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/usr/local/lib/node_modules/uber-cli/node_modules/uber-client/build/index.js:4:19)

**Comment by markmark1** [comment]
xx@xxs-Macbook-Air-3 ~ $ node --version
v0.10.31
xx@xxs-Macbook-Air-3 ~ $ npm --version
4.2.0
xx@xxs-Macbook-Air-3 ~ $

**Comment by jaebradley** [comment]
@markmark1 might be related to [this issue](https://github.com/lebab/lebab/issues/34) and more particularly [this comment](https://github.com/lebab/lebab/issues/34#issuecomment-94061578). Basically, it seems that `Symbol` was added to `node v0.12.0`.

**Comment by sjs7007** [comment]
Faced the same issue and posted fix [here](https://github.com/jaebradley/uber-cli/issues/27). Also pasting the solution here : 

Fixed by updating nodejs using instructions listed below from [this](http://stackoverflow.com/a/19584407/1462664) stackoverflow answer.

1. Clear NPM's cache:
```
sudo npm cache clean -f
```

2. Install a little helper called 'n'
```
sudo npm install -g n
```
3. Install latest stable Node.js version
```
sudo n stable
```

**Comment by jaebradley** [comment]
@sjs7007 thanks for the helpful instructions both here and in #27. @markmark1 I'm going to close this for now - if still find issues after following @sjs7007 's instructions feel free to reopen.
