### ISSUE TITLE
`uber -V` reports incorrect version

### ISSUE THREAD

**Issue by dylanpyle** [jaebradley/uber-cli#24]
(Following up from #20)

```
$ npm view uber-cli version
0.0.2

$ uber -V
0.0.1
```

Seems like the version is hardcoded here: https://github.com/jaebradley/uber-cli/blob/master/src/executables/uber.js#L5

**Comment by jaebradley** [comment]
@dylanpyle I'm thinking about just removing this flag entirely (mostly so that situations like this don't happen). Will be a breaking change, but I don't user impact will be minimal. Any strong preferences one way or the other?

**Comment by dylanpyle** [comment]
@jaebradley That's fine with me; I might consider something like #25 also though. Personally I'm a big fan of CLI utilities having `--version` flags that work.
