### ISSUE TITLE
price estimates over 100 miles

### ISSUE THREAD

**Issue by chrismccoy** [jaebradley/uber-cli#54]
i see if i do a price estimate over 100 miles, it errors out.
 
    (node:23928) UnhandledPromiseRejectionWarning: Error: StatusCodeError: 422 - {"fields":{"start_longitude":"Distance between two points exceeds 100 miles","end_longitude":"Distance between two points exceeds 100 miles","start_latitude":"Distance between two points exceeds 100 miles","end_latitude":"Distance between two points exceeds 100 miles"},"message":"Distance between two points exceeds 100 miles","code":"distance_exceeded"}

**Comment by jaebradley** [comment]
This is [an expected error code](https://developer.uber.com/docs/riders/references/api/v1.2/estimates-price-get#http-error-codes)

![image](https://user-images.githubusercontent.com/8136030/40013913-f718cc4c-577c-11e8-9419-0fdada7ea195.png)

Is your issue regarding the application handling the error with more grace? If so, I definitely agree!
