### ISSUE TITLE
It does not look like international currencies are getting converted properly

### ISSUE THREAD

**Issue by jaebradley** [jaebradley/uber-cli#73]
![image](https://user-images.githubusercontent.com/8136030/43730634-9aca3caa-9971-11e8-8d17-17ea1da0d17a.png)

**Comment by the-pat** [comment]
@jaebradley, it looks like the currencies are getting converted correctly. It appears `MX$` is a symbol for the Mexican peso. I used two other currencies to test the currency conversion:
![france](https://user-images.githubusercontent.com/22896198/47041712-29e07e80-d14f-11e8-9c8e-3fea9f3f1cfc.png)
![japan](https://user-images.githubusercontent.com/22896198/47041713-29e07e80-d14f-11e8-86dc-ca1ed684575e.png)

Hope this helps!

**Comment by jaebradley** [comment]
@the-pat thanks for verifying this! I think we can close this!
